#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
builder = Gtk.Builder()
builder.add_from_file("splashscreen.glade")
window = builder.get_object("splashscreen")
window.show_all()
Gtk.main()
